"""
SignalItem v3 — unified data model.
New in v3: expanded Track taxonomy (A/B/C/Hardware/Tech/Multimodal/Lifestyle),
           full_profile field for enriched items, sourcing_status for Bitable sync.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Literal, Optional
import hashlib

Track = Literal["A", "B", "C", "Hardware", "Tech", "Multimodal", "Lifestyle", "unknown"]
FeedbackState = Literal["interested", "ignored", "watchlist", "follow_up", "pending"]


@dataclass
class TeamInfo:
    founders: list[str] = field(default_factory=list)   # ["Alice Wang (ex-Stripe)"]
    company_size: str = ""                                # "5-10"
    founded_year: Optional[int] = None
    location: str = ""
    linkedin_urls: list[str] = field(default_factory=list)
    is_chinese_heritage: bool = False
    funding_info: str = ""                                # "Seed $2M a16z 2025-03"
    notes: str = ""                                       # LLM-extracted summary


@dataclass
class TrafficData:
    domain: str = ""
    total_visits: int = 0
    mom_growth_pct: float = 0.0
    snapshot_date: str = ""
    traffic_spike: bool = False
    is_new_product: bool = False


@dataclass
class ScoreBreakdown:
    ai_native: int = 0      # 0-30
    niche: int = 0          # 0-25
    business: int = 0       # 0-20
    team: int = 0           # 0-15
    bonus: int = 0          # 0-10
    penalty: int = 0        # 0-10
    total: int = 0
    reason: str = ""
    plus: list[str] = field(default_factory=list)
    minus: list[str] = field(default_factory=list)


@dataclass
class FullProfile:
    """Rich profile generated by S3 enrichment for high-score items (score >= threshold)."""
    # One-liner for Feishu / web header
    one_liner: str = ""
    # 2-3 sentence Chinese overview
    overview_zh: str = ""
    # What's innovative about the business model
    biz_model_zh: str = ""
    # Why this is interesting / what's the niche insight
    insight_zh: str = ""
    # Score narrative: what's good, what's bad in Creekstone framework
    score_narrative_zh: str = ""
    # Raw metrics table (GitHub stars growth, PH scores, etc.)
    metrics_summary: str = ""
    # Founder info (filled by on-demand enrichment when Gary clicks "扒 Founder")
    founder_detail: str = ""
    # Funding info
    funding_rounds: str = ""
    # Related links
    links: list[str] = field(default_factory=list)


@dataclass
class SignalItem:
    # ── Identity ──────────────────────────────────────────────────────────────
    id: str
    source: str
    collected_at: str     # ISO-8601 UTC

    # ── Core content ──────────────────────────────────────────────────────────
    title: str
    url: str
    description_en: str = ""
    description_zh: str = ""
    keywords: list[str] = field(default_factory=list)

    # ── Investment classification ──────────────────────────────────────────────
    track: Track = "unknown"
    track_reason: str = ""
    track_confidence: str = "low"
    fde_index: int = 0              # 0-10, Track B only
    fde_stage: str = ""             # "single_tool"|"accumulating"|"flywheel"|"achieved"

    # ── Scoring ───────────────────────────────────────────────────────────────
    score: float = 0.0
    score_breakdown: Optional[ScoreBreakdown] = None

    # ── Enrichment ────────────────────────────────────────────────────────────
    team: Optional[TeamInfo] = None
    traffic: Optional[TrafficData] = None
    full_profile: Optional[FullProfile] = None

    # ── Signal flags ──────────────────────────────────────────────────────────
    is_new: bool = False
    is_trending: bool = False
    is_spike: bool = False
    wow_growth_pct: Optional[float] = None
    has_video: bool = False

    # ── Human feedback ────────────────────────────────────────────────────────
    feedback_state: FeedbackState = "pending"
    feedback_note: str = ""         # Gary's free-text note from web UI
    sourcing_synced: bool = False   # whether pushed to Feishu Bitable sourcing table

    # ── Source metrics (raw) ──────────────────────────────────────────────────
    metrics: dict[str, Any] = field(default_factory=dict)
    thumbnail_url: Optional[str] = None
    raw: dict[str, Any] = field(default_factory=dict)


def make_id(source: str, url: str) -> str:
    key = f"{source}::{url.rstrip('/').lower()}"
    return hashlib.sha1(key.encode()).hexdigest()[:16]


def extract_domain(url: str) -> str:
    import re
    m = re.search(r"(?:https?://)?(?:www\.)?([^/\s?#]+)", url.lower())
    return m.group(1) if m else ""
